spring.application.name=note-manager

# Treat this service as an OAuth2 Resource Server that validates
# JWT access tokens issued by your Cognito user pool.
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.eu-north-1.amazonaws.com/eu-north-1_Oe4Ubp5pI

